import type { Season } from "./game";

export type TimelineKind = "battle" | "event" | "disaster";
export type DatePrecision = "year" | "season" | "month" | "exact-date";
export type TimelineCopy = { en: string; th: string };
export type HistoricalScope = "national" | "provincial" | "disaster";

export type HistoricalTimelineRecord = {
  id: string;
  kind: TimelineKind;
  scope: HistoricalScope;
  year: number;
  precision: DatePrecision;
  season?: Season;
  month?: number;
  day?: number;
  date: TimelineCopy;
  title: TimelineCopy;
  summary: TimelineCopy;
  regionKeys: string[];
  source: { label: string; url: string };
};

export type HistoricalYearLedger = {
  year: number;
  status: "reviewed-events" | "no-reviewed-event";
  recordIds: string[];
};

/**
 * “66 provinces + two islands” is the project’s stated Sengoku count. Iki and
 * Tsushima are deliberately tracked separately as island provinces, rather
 * than silently disappearing from map/timeline lookups.
 */
export const SENGOKU_66_PROVINCE_IDS = [
  "yamashiro", "yamato", "kawachi", "izumi", "settsu", "iga", "ise", "shima", "kii", "awaji", "omi", "wakasa", "echizen", "kaga", "noto", "etchu", "echigo", "sado", "tanba", "tango", "tajima", "harima", "mimasaka", "bizen", "bitchu", "bingo", "aki", "suo", "nagato", "iwami", "izumo", "hoki", "inaba", "oki", "iyo", "sanuki", "awa-shikoku", "tosa", "chikuzen", "chikugo", "hizen", "higo", "buzen", "bungo", "hyuga", "satsuma", "osumi", "owari", "mikawa", "totomi", "suruga", "izu", "kai", "sagami", "musashi", "kozuke", "shimotsuke", "hitachi", "shimosa", "kazusa", "awa-boso", "mino", "hida", "shinano", "dewa", "mutsu",
] as const;
export const SENGOKU_ISLAND_PROVINCE_IDS = ["iki", "tsushima"] as const;
export type SengokuProvinceId = typeof SENGOKU_66_PROVINCE_IDS[number] | typeof SENGOKU_ISLAND_PROVINCE_IDS[number];

const ufirst = (year: number) => ({ label: `Sengoku Shogun Map · ${year}`, url: `https://ufirst.jp/sengoku-map/en/${year}` });
const disasterArchive = { label: "University of Tokyo Historiographical Institute · 藤木久志 編『日本中世気象災害史年表稿』 (CC BY 4.0)", url: "https://www.hi.u-tokyo.ac.jp/collection/digitalgallery/disaster_events/about" };
const nationalArchives = { label: "National Archives of Japan · Tenka Taihen chronology", url: "https://www.archives.go.jp/exhibition/digital/tenkataihen/history.html" };
const tottoriArchives = { label: "Tottori Prefectural Archives · Inaba/Hōki Sengoku local history", url: "https://www.pref.tottori.lg.jp/item/413641.htm" };
const yasugiTourism = { label: "Yasugi Tourism Association · Rise and fall of the Amago clan", url: "https://yasugi-kankou.com/en/the-rise-and-fall-of-the-amago-clan/" };
const yamaguchiCulturalProperty = { label: "Yamaguchi Prefecture · Chōshū domain chronology", url: "https://bunkazai.pref.yamaguchi.lg.jp/support/theme/tyousyuu/tnen.html" };
const takayamaCityMuseum = { label: "Takayama City Museum · Kanamori Nagachika sites", url: "https://www.city.takayama.lg.jp/machihaku/1005305/1020397.html" };
const sadoCityWorldHeritage = { label: "Sado City · Sado Island Gold Mines", url: "https://www.city.sado.niigata.jp/site/mine/" };
const awajiCulturalHistoryMuseum = { label: "Awaji Cultural History Museum · Shirasu Castle", url: "https://awajishimamuseum.com/shirasujo/" };
const tobaCityCulturalHeritage = { label: "Toba City · Kuki Yoshitaka and the Kuki navy", url: "https://www.city.toba.mie.jp/isan/7686.html" };
const maizuruMunicipalSchool = { label: "Maizuru Municipal Yuragawa Elementary School · Local history", url: "https://yuragawa-maizuru.edumap.jp/tiiki" };
const nagasakiCulturalProperty = { label: "Nagasaki Prefecture Cultural Property Database · Katsumoto Castle", url: "https://www.pref.nagasaki.jp/bunkadb/index.php/view/532" };
const kyotoCityTourism = { label: "Kyoto City Official Travel Guide · Funaokayama battlefield site", url: "https://ja.kyoto.travel/tourism/single02.php?category_id=9&tourism_id=4" };
const yamaguchiCityTourism = { label: "Yamaguchi City Official Tourism · Ōuchi clan chronology", url: "https://yamaguchi-city.jp/history/ouchi_chronology.html" };

const copy = (en: string, th: string): TimelineCopy => ({ en, th });
const record = (id: string, kind: TimelineKind, scope: HistoricalScope, year: number, precision: DatePrecision, title: TimelineCopy, summary: TimelineCopy, regionKeys: string[], source: { label: string; url: string }, date = copy(`${year}`, `ค.ศ. ${year}`), details: Partial<Pick<HistoricalTimelineRecord, "season" | "month" | "day">> = {}): HistoricalTimelineRecord => ({ id, kind, scope, year, precision, date, title, summary, regionKeys, source, ...details });

/**
 * A curated, citable seed. A blank year is recorded as blank in YEAR_LEDGER;
 * it is never backfilled with model-generated “history”. The catalogue is
 * deliberately append-only so research can grow province by province.
 */
export const HISTORICAL_TIMELINE: HistoricalTimelineRecord[] = [
  record("1467-onin-war", "event", "national", 1467, "year", copy("Outbreak of the Ōnin War", "การเริ่มสงครามโอนิง"), copy("Factional conflict in Kyoto began the long political breakdown conventionally used as the opening of the Sengoku era.", "ความขัดแย้งระหว่างฝ่ายในเกียวโตเริ่มขึ้น และมักใช้เป็นจุดเปิดของยุคเซ็นโกคุ."), ["yamashiro"], ufirst(1467)),
  record("1477-onin-war-end", "event", "national", 1477, "year", copy("End of the Ōnin War", "การสิ้นสุดสงครามโอนิง"), copy("The conflict ended without restoring a stable national political order.", "สงครามยุติลงโดยไม่ได้ฟื้นระเบียบการเมืองระดับชาติให้มั่นคง."), ["yamashiro"], ufirst(1477)),
  record("1488-kaga-ikki", "event", "provincial", 1488, "year", copy("Kaga Ikkō-ikki takes power", "อิกโคอิกกิยึดอำนาจในคางะ"), copy("The Kaga uprising is recorded as a provincial political rupture rather than a player-facing event.", "การลุกฮือในคางะเป็นรอยร้าวทางการเมืองระดับแคว้น ไม่ใช่เหตุการณ์ที่บังคับผู้เล่นให้เกี่ยวข้อง."), ["kaga"], ufirst(1488)),
  record("1493-meio-disturbance", "event", "national", 1493, "year", copy("Meiō Disturbance", "ความวุ่นวายเมโอ"), copy("A Kyoto political coup reshaped the balance among Muromachi actors.", "รัฐประหารทางการเมืองในเกียวโตเปลี่ยนดุลระหว่างกลุ่มอำนาจมุโรมาจิ."), ["yamashiro"], ufirst(1493)),
  record("1531-nakajima-war", "battle", "provincial", 1531, "year", copy("Battle of Nakajima", "ศึกนากาจิมะ"), copy("Conflict among Hongan-ji and allied forces affected the Kinai political field.", "ความขัดแย้งระหว่างกลุ่มฮงกันจิกับพันธมิตรส่งผลต่อสนามการเมืองคิไน."), ["settsu"], ufirst(1531)),
  record("1543-firearms-tanegashima", "event", "national", 1543, "year", copy("Firearms reach Tanegashima", "อาวุธปืนมาถึงทาเนงาชิมะ"), copy("The introduction is catalogued as national technological context; it does not grant equipment to a campaign.", "การเข้ามาของอาวุธปืนเป็นบริบทเทคโนโลยีระดับชาติ ไม่ได้มอบอุปกรณ์ให้แคมเปญโดยอัตโนมัติ."), ["osumi"], ufirst(1543)),
  record("1546-kawagoe", "battle", "provincial", 1546, "year", copy("Battle of Kawagoe", "ศึกคาวาโกเอะ"), copy("A major Kantō conflict associated with the Later Hōjō position.", "ความขัดแย้งสำคัญในคันโตที่เกี่ยวข้องกับฐานอำนาจโฮโจยุคหลัง."), ["musashi"], ufirst(1546)),
  record("1548-uedahara", "battle", "provincial", 1548, "year", copy("Battle of Uedahara", "ศึกอูเอดาฮาระ"), copy("A Shinano campaign record used only as regional war context.", "บันทึกศึกในชินาโนะ ใช้เป็นบริบทสงครามระดับแคว้นเท่านั้น."), ["shinano"], ufirst(1548)),
  record("1549-xavier-kagoshima", "event", "provincial", 1549, "year", copy("Francis Xavier arrives at Kagoshima", "ฟรานซิส ซาเวียร์มาถึงคาโงชิมะ"), copy("Christian contact in Satsuma is historical context, not a required plot for the player.", "การติดต่อคริสต์ศาสนาในซัตสึมะเป็นบริบทประวัติศาสตร์ ไม่ใช่พล็อตบังคับผู้เล่น."), ["satsuma"], ufirst(1549)),
  record("1555-itsukushima", "battle", "provincial", 1555, "month", copy("Battle of Itsukushima", "ศึกอิสึกูชิมะ"), copy("Mōri Motonari defeated Sue Harukata, accelerating the Mōri rise in western Honshū.", "โมริ โมโตนาริชนะซุเอะ ฮารุกาตะ ส่งผลให้โมริเติบโตในฮนชูตะวันตก."), ["aki"], ufirst(1555), copy("Month 10 · 1555", "เดือน 10 · ค.ศ. 1555"), { month: 10, season: "Autumn" }),
  record("1556-nagara-river", "battle", "provincial", 1556, "year", copy("Battle of Nagara River", "ศึกแม่น้ำนางาระ"), copy("The Mino succession struggle is recorded as provincial context.", "การแย่งชิงอำนาจในมิโนะถูกบันทึกเป็นบริบทระดับแคว้น."), ["mino"], ufirst(1556)),
  record("1560-okehazama", "battle", "national", 1560, "year", copy("Battle of Okehazama", "ศึกโอเคฮาซามะ"), copy("Oda Nobunaga defeated Imagawa Yoshimoto in Owari, shifting the central Japanese balance.", "โอดะ โนบุนางะชนะอิมางาวะ โยชิโมโตะในโอวาริ ทำให้ดุลอำนาจภาคกลางเปลี่ยนไป."), ["owari"], ufirst(1560)),
  record("1561-kawanakajima-fourth", "battle", "provincial", 1561, "year", copy("Fourth Battle of Kawanakajima", "ศึกคาวานากาจิมะครั้งที่สี่"), copy("A Shinano battle in the Takeda–Uesugi conflict.", "ศึกในชินาโนะของความขัดแย้งทาเคดะ–อุเอสึงิ."), ["shinano"], ufirst(1561)),
  record("1564-mikawa-ikko-ikki", "event", "provincial", 1564, "year", copy("Mikawa Ikkō-ikki suppressed", "การปราบอิกโคอิกกิในมิกาวะ"), copy("A local religious-political conflict became a key Mikawa context.", "ความขัดแย้งศาสนา–การเมืองท้องถิ่นกลายเป็นบริบทสำคัญของมิกาวะ."), ["mikawa"], ufirst(1564)),
  record("1565-eiroku-incident", "event", "national", 1565, "year", copy("Eiroku Incident", "เหตุการณ์เอโรคุ"), copy("The shogun’s death is treated as national political context centered on Kyoto.", "การสิ้นพระชนม์ของโชกุนเป็นบริบทการเมืองระดับชาติที่มีศูนย์กลางในเกียวโต."), ["yamashiro"], ufirst(1565)),
  record("1567-inabayama", "battle", "provincial", 1567, "year", copy("Fall of Inabayama Castle", "การแตกของปราสาทอินาบายามะ"), copy("Oda control of Mino became a major central route context.", "การควบคุมมิโนะของโอดะกลายเป็นบริบทสำคัญของเส้นทางภาคกลาง."), ["mino"], ufirst(1567)),
  record("1568-oda-kyoto", "event", "national", 1568, "year", copy("Oda enters Kyoto", "โอดะเข้าสู่เกียวโต"), copy("Nobunaga’s Kyoto entry changed the national political field.", "การเข้าสู่เกียวโตของโนบุนางะเปลี่ยนสนามการเมืองระดับชาติ."), ["yamashiro"], ufirst(1568)),
  record("1569-honkokuji-incident", "event", "national", 1569, "year", copy("Honkoku-ji Incident", "เหตุการณ์ฮงโคคุจิ"), copy("The year view records an attack on Ashikaga Yoshiaki's temporary residence at Honkoku-ji and its defense before Nobunaga returned to Kyoto.", "บันทึกประจำปีระบุการโจมตีที่พำนักชั่วคราวของอาชิคางะ โยชิอากิ ณ ฮงโคคุจิ และการตั้งรับก่อนโนบุนางะกลับถึงเกียวโต."), ["yamashiro"], ufirst(1569)),
  record("1569-nijo-palace", "event", "national", 1569, "year", copy("Nijō Palace built for Ashikaga Yoshiaki", "การสร้างตำหนักนิโจสำหรับอาชิคางะ โยชิอากิ"), copy("The source lists construction of a fortified Nijō residence but does not provide a month.", "แหล่งข้อมูลระบุการสร้างที่พำนักนิโจที่มีการป้องกัน แต่ไม่ให้เดือน."), ["yamashiro"], ufirst(1569), copy("1569 · month not specified", "ค.ศ. 1569 · ไม่ระบุเดือน")),
  record("1570-kanegasaki-retreat", "event", "national", 1570, "month", copy("Retreat at Kanegasaki", "การถอยทัพที่คาเนงาซากิ"), copy("The source places the retreat during the Echizen campaign after Azai Nagamasa's defection became apparent.", "หน้าปีระบุการถอยทัพระหว่างศึกเอจิเซ็น หลังการแตกจากฝ่ายของอาซาอิ นางามาซะปรากฏชัด."), ["omi", "echizen"], ufirst(1570), copy("Spring · month 4", "วสันต์ · เดือน 4"), { season: "Spring", month: 4 }),
  record("1570-anegawa", "battle", "national", 1570, "exact-date", copy("Battle of Anegawa", "ศึกอาเนงาวะ"), copy("The Oda–Tokugawa alliance defeated the Azai–Asakura alliance in Ōmi; the source notes that the Azai were not destroyed by the battle.", "พันธมิตรโอดะ–โทกูงาวะชนะพันธมิตรอาซาอิ–อาซากูระในโอมิ โดยแหล่งข้อมูลระบุว่าอาซาอิไม่ได้ถูกทำลายลงด้วยศึกครั้งนี้."), ["omi"], ufirst(1570), copy("30 July 1570", "30 กรกฎาคม ค.ศ. 1570"), { season: "Summer", month: 7, day: 30 }),
  record("1570-ishiyama-war", "event", "national", 1570, "month", copy("Outbreak of the Ishiyama War", "การเริ่มสงครามอิชิยามะ"), copy("The source records the rise of Ishiyama Hongan-ji in Settsu against Nobunaga.", "แหล่งข้อมูลบันทึกการลุกขึ้นของอิชิยามะฮงกันจิในเซ็ตสึเพื่อต่อต้านโนบุนางะ."), ["settsu"], ufirst(1570), copy("Summer · month 8", "คิมหันต์ · เดือน 8"), { season: "Summer", month: 8 }),
  record("1570-noda-fukushima", "battle", "provincial", 1570, "month", copy("Battle of Noda–Fukushima", "ศึกโนดะ–ฟูกูชิมะ"), copy("The year view places fighting in Settsu around the strongholds of Noda and Fukushima.", "หน้าปีวางการสู้รบในเซ็ตสึรอบฐานที่มั่นโนดะและฟูกูชิมะ."), ["settsu"], ufirst(1570), copy("Autumn · month 9", "สารท · เดือน 9"), { season: "Autumn", month: 9 }),
  record("1571-mount-hiei", "event", "national", 1571, "year", copy("Burning of Mount Hiei", "การเผาภูเขาฮิเอ"), copy("The conflict around Enryaku-ji is catalogued as Kyoto–Ōmi political and military context.", "ความขัดแย้งรอบเอ็นเรียคุจิถูกเก็บเป็นบริบทการเมืองและสงครามของเกียวโต–โอมิ."), ["yamashiro", "omi"], ufirst(1571)),
  record("1572-mikatagahara", "battle", "national", 1572, "year", copy("Battle of Mikatagahara", "ศึกมิคาตากาฮาระ"), copy("Takeda and Tokugawa forces fought in Tōtōmi.", "กองกำลังทาเคดะและโทกูงาวะสู้รบกันในโทโตมิ."), ["totomi"], ufirst(1572)),
  record("1573-muromachi-fall", "event", "national", 1573, "year", copy("End of the Muromachi shogunate", "การสิ้นสุดโชกุนมุโรมาจิ"), copy("Ashikaga Yoshiaki’s expulsion from Kyoto is used as national political context.", "การขับอาชิคางะ โยชิอากิออกจากเกียวโตใช้เป็นบริบทการเมืองระดับชาติ."), ["yamashiro"], ufirst(1573)),
  record("1575-nagashino", "battle", "national", 1575, "year", copy("Battle of Nagashino", "ศึกนางาชิโนะ"), copy("A Mikawa battle in the Oda–Tokugawa and Takeda conflict.", "ศึกในมิกาวะของความขัดแย้งโอดะ–โทกูงาวะกับทาเคดะ."), ["mikawa"], ufirst(1575)),
  record("1576-azuchi", "event", "national", 1576, "year", copy("Azuchi Castle construction begins", "เริ่มสร้างปราสาทอาซูจิ"), copy("Azuchi is a central political and material-culture context in Ōmi.", "อาซูจิเป็นบริบทการเมืองและวัฒนธรรมวัตถุสำคัญในโอมิ."), ["omi"], ufirst(1576)),
  record("1577-western-campaign", "battle", "provincial", 1577, "year", copy("Hashiba campaign in Harima", "การทัพฮาชิบะในฮาริมะ"), copy("Western campaign pressure is regional context for Harima routes.", "แรงกดดันจากการทัพตะวันตกเป็นบริบทเส้นทางของฮาริมะ."), ["harima"], ufirst(1577)),
  record("1578-araki-rebellion", "event", "provincial", 1578, "year", copy("Araki Murashige rebellion", "การกบฏของอารากิ มูราชิเงะ"), copy("The Settsu conflict is recorded as a regional fracture within Oda power.", "ความขัดแย้งในเซ็ตสึถูกบันทึกเป็นรอยร้าวระดับแคว้นภายในอำนาจโอดะ."), ["settsu"], ufirst(1578)),
  record("1580-ishiyama-end", "event", "national", 1580, "year", copy("End of the Ishiyama War", "การสิ้นสุดสงครามอิชิยามะ"), copy("The prolonged conflict around Ishiyama Hongan-ji ended; the catalog does not infer a player consequence.", "ความขัดแย้งยืดเยื้อรอบอิชิยามะฮงกันจิสิ้นสุดลง โดย catalog ไม่อนุมานผลต่อผู้เล่น."), ["settsu"], ufirst(1580)),
  record("1582-honnoji", "event", "national", 1582, "year", copy("Honnō-ji Incident", "เหตุการณ์ฮนโนจิ"), copy("The year view places Nobunaga’s death at Honnō-ji at the center of a succession crisis.", "หน้าปีวางการเสียชีวิตของโนบุนางะที่ฮนโนจิเป็นศูนย์กลางของวิกฤตสืบทอดอำนาจ."), ["yamashiro"], ufirst(1582)),
  record("1582-yamazaki", "battle", "national", 1582, "year", copy("Battle of Yamazaki", "ศึกยามาซากิ"), copy("Hideyoshi defeated Akechi Mitsuhide after the Honnō-ji Incident.", "ฮิเดโยชิชนะอาเคจิ มิสึฮิเดะหลังเหตุการณ์ฮนโนจิ."), ["yamashiro"], ufirst(1582)),
  record("1583-shizugatake", "battle", "national", 1583, "year", copy("Battle of Shizugatake", "ศึกชิซูกาตาเกะ"), copy("A succession conflict battle tied to northern Ōmi.", "ศึกแย่งชิงอำนาจที่เกี่ยวข้องกับโอมิตอนเหนือ."), ["omi"], ufirst(1583)),
  record("1584-komaki-nagakute", "battle", "national", 1584, "year", copy("Komaki and Nagakute Campaign", "การทัพโคมากิและนางากูเตะ"), copy("Fighting in Owari and Mikawa formed a major post-Nobunaga contest.", "การสู้รบในโอวาริและมิกาวะเป็นการแข่งขันสำคัญหลังโนบุนางะ."), ["owari", "mikawa"], ufirst(1584)),
  record("1585-shikoku", "battle", "national", 1585, "year", copy("Hideyoshi’s Shikoku campaign", "การทัพชิโกกุของฮิเดโยชิ"), copy("The campaign affected the Shikoku provincial political field.", "การทัพส่งผลต่อสนามการเมืองระดับแคว้นของชิโกกุ."), ["iyo", "sanuki", "awa-shikoku", "tosa"], ufirst(1585)),
  record("1586-tensho-earthquake", "disaster", "disaster", 1586, "year", copy("Tenshō earthquake", "แผ่นดินไหวเท็นโช"), copy("A major earthquake is retained as historical environmental context; this catalog does not state a day where the cited record has not been locally reviewed.", "แผ่นดินไหวใหญ่ถูกเก็บเป็นบริบทสิ่งแวดล้อมทางประวัติศาสตร์ โดย catalog นี้ไม่ระบุวันหากยังไม่ได้ตรวจแหล่งในพื้นที่."), ["mino", "omi", "kai"], disasterArchive),
  record("1587-kyushu", "battle", "national", 1587, "year", copy("Hideyoshi’s Kyūshū campaign", "การทัพคิวชูของฮิเดโยชิ"), copy("A national campaign with provincial effects in northern and southern Kyūshū.", "การทัพระดับชาติที่มีผลระดับแคว้นในคิวชูเหนือและใต้."), ["chikuzen", "chikugo", "hizen", "higo", "buzen", "bungo", "hyuga", "satsuma", "osumi"], ufirst(1587)),
  record("1590-odawara", "battle", "national", 1590, "year", copy("Siege of Odawara", "การล้อมโอดาวาระ"), copy("The campaign against the Later Hōjō is a Kantō and national transition context.", "การทัพต่อโฮโจยุคหลังเป็นบริบทเปลี่ยนผ่านของคันโตและระดับชาติ."), ["sagami", "musashi", "kozuke", "shimotsuke", "hitachi", "shimosa", "kazusa", "awa-boso"], ufirst(1590)),
  record("1592-korea-campaign", "event", "national", 1592, "year", copy("First Korean campaign begins", "เริ่มการทัพเกาหลีครั้งแรก"), copy("The overseas campaign is national context; it does not make a local player a participant.", "การทัพโพ้นทะเลเป็นบริบทระดับชาติ ไม่ได้ทำให้ผู้เล่นท้องถิ่นเป็นผู้เข้าร่วมโดยอัตโนมัติ."), ["chikuzen", "hizen"], ufirst(1592)),
  record("1596-keicho-fushimi-earthquake", "disaster", "disaster", 1596, "year", copy("Keichō–Fushimi earthquake", "แผ่นดินไหวเคโช–ฟูชิมิ"), copy("A late Sengoku earthquake record retained as environmental context around Kyoto and Kinai.", "บันทึกแผ่นดินไหวปลายเซ็นโกคุที่เก็บเป็นบริบทสิ่งแวดล้อมรอบเกียวโตและคิไน."), ["yamashiro", "settsu", "kawachi", "izumi"], disasterArchive),
  record("1597-korea-campaign", "event", "national", 1597, "year", copy("Second Korean campaign begins", "เริ่มการทัพเกาหลีครั้งที่สอง"), copy("The resumed overseas war is national context with port and logistics pressure.", "สงครามโพ้นทะเลที่กลับมาเป็นบริบทระดับชาติที่สร้างแรงกดดันท่าเรือและลอจิสติกส์."), ["chikuzen", "hizen"], ufirst(1597)),
  record("1598-hideyoshi-death", "event", "national", 1598, "year", copy("Death of Toyotomi Hideyoshi", "การเสียชีวิตของโทโยโตมิ ฮิเดโยชิ"), copy("Hideyoshi’s death shifted the national political balance without dictating a character’s private story.", "การเสียชีวิตของฮิเดโยชิเปลี่ยนดุลการเมืองระดับชาติ โดยไม่กำหนดเรื่องส่วนตัวของตัวละคร."), ["yamashiro"], ufirst(1598)),
  record("1600-fushimi", "battle", "national", 1600, "month", copy("Siege of Fushimi Castle", "การล้อมปราสาทฟูชิมิ"), copy("The source places the siege in month 7 after Ieyasu marched toward Aizu.", "แหล่งข้อมูลวางการล้อมไว้ในเดือน 7 หลังอิเอยาสึเคลื่อนทัพสู่อาอิซึ."), ["yamashiro"], ufirst(1600), copy("Month 7 · 1600", "เดือน 7 · ค.ศ. 1600"), { month: 7, season: "Summer" }),
  record("1600-sekigahara", "battle", "national", 1600, "exact-date", copy("Battle of Sekigahara", "ศึกเซกิงาฮาระ"), copy("The Eastern Army under Tokugawa Ieyasu defeated the Western Army in Mino.", "กองทัพฝ่ายตะวันออกของโทกูงาวะ อิเอยาสึชนะฝ่ายตะวันตกในมิโนะ."), ["mino"], ufirst(1600), copy("21 October 1600", "21 ตุลาคม ค.ศ. 1600"), { month: 10, season: "Autumn", day: 21 }),
  record("1603-edo-shogunate", "event", "national", 1603, "year", copy("Tokugawa shogunate established", "การสถาปนาโชกุนโทกูงาวะ"), copy("The National Archives chronology records the opening of the Edo shogunate in 1603.", "ลำดับเหตุการณ์ของหอจดหมายเหตุแห่งชาติบันทึกการเปิดโชกุนเอโดะใน ค.ศ. 1603."), ["musashi", "yamashiro"], nationalArchives),
  record("1614-osaka-winter", "battle", "national", 1614, "year", copy("Siege of Osaka: Winter Campaign", "การล้อมโอซากะ: การทัพฤดูหนาว"), copy("The Osaka conflict is national context concentrated in Settsu.", "ความขัดแย้งโอซากะเป็นบริบทระดับชาติที่กระจุกในเซ็ตสึ."), ["settsu"], ufirst(1614)),
  record("1615-osaka-summer", "battle", "national", 1615, "year", copy("Siege of Osaka: Summer Campaign", "การล้อมโอซากะ: การทัพฤดูร้อน"), copy("The destruction of Toyotomi resistance concludes the catalog’s stated Sengoku range.", "การทำลายการต่อต้านของโทโยโตมิเป็นจุดสิ้นสุดช่วงเซ็นโกคุที่ catalog นี้กำหนด."), ["settsu"], ufirst(1615)),
  record("1586-musashi-persistent-ice", "disaster", "disaster", 1586, "exact-date", copy("Persistent ice recorded in Musashi", "บันทึกน้ำแข็งคงอยู่นานในมูซาชิ"), copy("A source record describes ice remaining into daylight in Musashi. It is local weather evidence, not an automatic campaign hazard.", "บันทึกแหล่งหนึ่งบรรยายว่าน้ำแข็งยังคงอยู่จนถึงเวลากลางวันในมูซาชิ ใช้เป็นหลักฐานอากาศท้องถิ่น ไม่ใช่ภัยที่เกิดกับแคมเปญโดยอัตโนมัติ."), ["musashi"], disasterArchive, copy("19 April 1586", "19 เมษายน ค.ศ. 1586"), { season: "Spring", month: 4, day: 19 }),
  record("1586-yamato-rain", "disaster", "disaster", 1586, "exact-date", copy("Rain after a dry spell in Yamato", "ฝนหลังช่วงแล้งในยามาโตะ"), copy("A Yamato diary records rainfall after a recent dry spell. The card does not infer harvest or travel effects beyond the source report.", "บันทึกจากยามาโตะระบุฝนหลังช่วงแล้งล่าสุด การ์ดนี้ไม่อนุมานผลต่อการเก็บเกี่ยวหรือการเดินทางเกินกว่ารายงานต้นทาง."), ["yamato"], disasterArchive, copy("16 May 1586", "16 พฤษภาคม ค.ศ. 1586"), { season: "Spring", month: 5, day: 16 }),
  record("1586-satsuma-flood", "disaster", "disaster", 1586, "exact-date", copy("Flood disrupts a troop movement in Satsuma", "น้ำท่วมขัดขวางการเคลื่อนกำลังในซัตสึมะ"), copy("A Satsuma record notes that flooding prevented an intended troop movement. This stays regional context and never assigns that movement to the player.", "บันทึกจากซัตสึมะระบุว่าน้ำท่วมทำให้การเคลื่อนกำลังที่ตั้งใจไว้ไม่เกิดขึ้น ใช้เป็นบริบทระดับแคว้น และไม่ผูกการเคลื่อนนั้นกับผู้เล่น."), ["satsuma"], disasterArchive, copy("28 May 1586", "28 พฤษภาคม ค.ศ. 1586"), { season: "Spring", month: 5, day: 28 }),
  record("1596-kozuke-snow", "disaster", "disaster", 1596, "exact-date", copy("Heavy snow in Kōzuke", "หิมะหนักในโคซูเกะ"), copy("A Kōzuke chronicle records heavy snow on the cited date. It is a source-bounded weather card, not a region-wide climate claim.", "พงศาวดารโคซูเกะบันทึกหิมะหนักในวันที่อ้างอิง เป็นการ์ดอากาศที่จำกัดตามแหล่ง ไม่ใช่คำอ้างภูมิอากาศทั้งแคว้น."), ["kozuke"], disasterArchive, copy("2 May 1596", "2 พฤษภาคม ค.ศ. 1596"), { season: "Spring", month: 5, day: 2 }),
  record("1596-owari-mino-flood", "disaster", "disaster", 1596, "exact-date", copy("Flooding recorded in Owari–Mino", "บันทึกน้ำท่วมในโอวาริ–มิโนะ"), copy("A chronicle records flooding for the Owari–Mino region. The catalog treats this as cross-province environmental context only.", "พงศาวดารบันทึกน้ำท่วมในภูมิภาคโอวาริ–มิโนะ โดย catalog ใช้เป็นบริบทสิ่งแวดล้อมข้ามแคว้นเท่านั้น."), ["owari", "mino"], disasterArchive, copy("4 June 1596", "4 มิถุนายน ค.ศ. 1596"), { season: "Summer", month: 6, day: 4 }),
  record("1596-bizen-harvest-report", "disaster", "disaster", 1596, "exact-date", copy("Good harvest report from Bizen", "รายงานผลเก็บเกี่ยวดีจากบิเซ็น"), copy("A source report describes a good harvest in Bizen. It cannot create money, supplies, or a reward without the campaign’s own economy rules.", "รายงานต้นทางกล่าวถึงผลเก็บเกี่ยวดีในบิเซ็น ข้อมูลนี้ไม่สร้างเงิน เสบียง หรือรางวัล หากกฎเศรษฐกิจของแคมเปญไม่ได้กำหนดไว้."), ["bizen"], disasterArchive, copy("22 June 1596", "22 มิถุนายน ค.ศ. 1596"), { season: "Summer", month: 6, day: 22 }),
  record("1596-echigo-earthquake-drought", "disaster", "disaster", 1596, "exact-date", copy("Earthquake and drought recorded in Echigo", "บันทึกแผ่นดินไหวและภัยแล้งในเอจิโงะ"), copy("An Echigo chronicle records both an earthquake and drought. The card preserves this paired source report without extrapolating damage.", "พงศาวดารเอจิโงะบันทึกทั้งแผ่นดินไหวและภัยแล้ง การ์ดคงรายงานคู่นี้ไว้โดยไม่ขยายความเสียหายเกินแหล่ง."), ["echigo"], disasterArchive, copy("2 July 1596", "2 กรกฎาคม ค.ศ. 1596"), { season: "Summer", month: 7, day: 2 }),
  record("1615-mutsu-snow-drought", "disaster", "disaster", 1615, "exact-date", copy("Snow and drought recorded in Mutsu", "บันทึกหิมะและภัยแล้งในมุตสึ"), copy("A Mutsu chronicle records snowfall and drought. Its separate note about Osaka belongs to national history and is not folded into this local weather card.", "พงศาวดารมุตสึบันทึกหิมะและภัยแล้ง ส่วนข้อความแยกเรื่องโอซากะเป็นประวัติศาสตร์ระดับชาติ จึงไม่ถูกผนวกเข้าการ์ดอากาศท้องถิ่นนี้."), ["mutsu"], disasterArchive, copy("15 May 1615", "15 พฤษภาคม ค.ศ. 1615"), { season: "Spring", month: 5, day: 15 }),
  record("1615-aizu-drought", "disaster", "disaster", 1615, "exact-date", copy("Drought recorded in Aizu", "บันทึกภัยแล้งในไอซุ"), copy("A source reports drought through June in Aizu. The campaign uses the Mutsu key for lookup but retains Aizu in copy as the source locality.", "แหล่งข้อมูลรายงานภัยแล้งยาวถึงเดือนมิถุนายนในไอซุ แคมเปญใช้รหัสมุตสึในการค้นหา แต่คงชื่อไอซุไว้ในข้อความในฐานะพื้นที่ของแหล่ง."), ["mutsu"], disasterArchive, copy("26 June 1615", "26 มิถุนายน ค.ศ. 1615"), { season: "Summer", month: 6, day: 26 }),
  record("1615-hizen-nagasaki-smallpox", "disaster", "disaster", 1615, "exact-date", copy("Smallpox mortality report from Nagasaki", "รายงานผู้เสียชีวิตจากไข้ทรพิษที่นางาซากิ"), copy("An archival report records smallpox mortality in Nagasaki. It remains a source-specific public-health note and never automatically creates an epidemic in play.", "บันทึกจดหมายเหตุรายงานผู้เสียชีวิตจากไข้ทรพิษในนางาซากิ ข้อมูลนี้เป็นหมายเหตุสาธารณสุขเฉพาะแหล่ง และไม่สร้างโรคระบาดในเกมโดยอัตโนมัติ."), ["hizen"], disasterArchive, copy("13 July 1615", "13 กรกฎาคม ค.ศ. 1615"), { season: "Summer", month: 7, day: 13 }),
  record("1615-yamashiro-flood", "disaster", "disaster", 1615, "exact-date", copy("Flood damage reported in Yamashiro", "รายงานความเสียหายน้ำท่วมในยามาชิโระ"), copy("A Yamashiro village report records flooding and extensive field loss. It is local archival context, not a mandatory player consequence.", "รายงานจากหมู่บ้านในยามาชิโระบันทึกน้ำท่วมและความเสียหายต่อที่นาในวงกว้าง เป็นบริบทจดหมายเหตุท้องถิ่น ไม่ใช่ผลบังคับต่อผู้เล่น."), ["yamashiro"], disasterArchive, copy("23 July 1615", "23 กรกฎาคม ค.ศ. 1615"), { season: "Summer", month: 7, day: 23 }),
  record("1510s-amago-hoki-advance", "event", "provincial", 1510, "season", copy("Amago advance into Hōki’s Hino district", "การรุกของอามาโกะสู่เขตฮิโนะแห่งโฮกิ"), copy("A prefectural archive describes Amago Tsunehisa’s advance from Izumo into Hōki during the 1510s–1520s. It is a decade-scale political context, not a dated battle card.", "หอจดหมายเหตุจังหวัดบรรยายการรุกของอามาโกะ สึเนฮิสะจากอิซุโมะสู่โฮกิในทศวรรษ 1510–1520 จึงเป็นบริบทการเมืองระดับทศวรรษ ไม่ใช่การ์ดศึกที่ลงวันได้."), ["izumo", "hoki"], tottoriArchives, copy("1510s–1520s · year not fixed", "ทศวรรษ 1510–1520 · ยังไม่ระบุปี")),
  record("1521-amago-sanin-sanyo-expansion", "event", "provincial", 1521, "year", copy("Amago regional expansion", "การขยายอำนาจภูมิภาคของอามาโกะ"), copy("A local overview dates Amago expansion across parts of San’in and San’yō to 1521. The record is a source-labelled regional context, not a province-by-province ownership map.", "แหล่งท้องถิ่นลงวันที่การขยายอำนาจของอามาโกะครอบคลุมบางส่วนของซันอินและซันโยไว้ที่ ค.ศ. 1521 บันทึกนี้เป็นบริบทภูมิภาคตามแหล่ง ไม่ใช่แผนที่ผู้ครองแคว้นรายจังหวัด."), ["aki", "bingo", "bitchu", "bizen", "mimasaka", "harima", "inaba", "hoki", "izumo", "iwami", "oki"], yasugiTourism),
  record("1562-mori-izumo-hoki-advance", "event", "provincial", 1562, "year", copy("Mōri advance toward Izumo and Hōki", "การรุกของโมริสู่อิซุโมะและโฮกิ"), copy("A prefectural archive records Mōri Motonari’s advance toward Izumo and Hōki and shifting local allegiance. This does not impose a political stance on the player.", "หอจดหมายเหตุจังหวัดบันทึกการรุกของโมริ โมโตนาริสู่ิซุโมะและโฮกิพร้อมการเปลี่ยนฝ่ายของกลุ่มท้องถิ่น ข้อมูลนี้ไม่บังคับจุดยืนทางการเมืองแก่ผู้เล่น."), ["izumo", "hoki"], tottoriArchives),
  record("1566-gassan-toda-fall", "event", "provincial", 1566, "year", copy("Surrender of Gassan Toda Castle", "การยอมจำนนของปราสาทกัสซันโทดะ"), copy("A local overview dates the surrender of Gassan Toda Castle and Amago Yoshihisa’s fall to 1566. The card deliberately omits unsourced siege detail.", "แหล่งท้องถิ่นลงวันที่การยอมจำนนของปราสาทกัสซันโทดะและการล่มของอามาโกะ โยชิฮิสะไว้ที่ ค.ศ. 1566 การ์ดนี้ตัดรายละเอียดการล้อมที่ไม่มีแหล่งรองรับ."), ["izumo"], yasugiTourism),
  record("1569-amago-revival", "event", "provincial", 1569, "year", copy("Amago revival movement", "ขบวนการฟื้นอามาโกะ"), copy("A prefectural archive records the Amago revival movement under Katsuhisa and Yamanaka in Izumo and Hōki. It is background only unless campaign evidence connects to it.", "หอจดหมายเหตุจังหวัดบันทึกขบวนการฟื้นอามาโกะภายใต้คัตสึฮิสะและยามานากะในอิซุโมะกับโฮกิ ใช้เป็นฉากหลังเท่านั้น เว้นแต่หลักฐานในแคมเปญเชื่อมถึงเหตุการณ์นี้."), ["izumo", "hoki"], tottoriArchives),
  record("1578-kozuki-fall", "battle", "provincial", 1578, "month", copy("Fall of Kōzuki Castle", "การแตกของปราสาทโคซึกิ"), copy("The Kōzuki Castle force fell in Harima in July 1578. Hōki leaders are documented among the Amago side, but Hōki is not represented as the battle location.", "กองกำลังที่ปราสาทโคซึกิในฮาริมะแตกในเดือนกรกฎาคม ค.ศ. 1578 มีการบันทึกผู้นำจากโฮกิอยู่ฝ่ายอามาโกะ แต่โฮกิไม่ถูกระบุว่าเป็นสถานที่ของศึก."), ["harima", "hoki"], tottoriArchives, copy("July 1578", "กรกฎาคม ค.ศ. 1578"), { season: "Summer", month: 7 }),
  record("1486-tsushima-flood", "disaster", "disaster", 1486, "exact-date", copy("Flood damage recorded in Tsushima", "บันทึกความเสียหายน้ำท่วมในสึชิมะ"), copy("A Tsushima chronicle records prolonged rain and flooding that damaged much of the cultivated land at Sasu. It is an archival locality record, not an island-wide simulation.", "พงศาวดารสึชิมะบันทึกฝนต่อเนื่องและน้ำท่วมที่ทำลายพื้นที่เพาะปลูกส่วนใหญ่ในซาซุ เป็นบันทึกเฉพาะพื้นที่ตามจดหมายเหตุ ไม่ใช่การจำลองทั้งเกาะ."), ["tsushima"], disasterArchive, copy("14 February 1486", "14 กุมภาพันธ์ ค.ศ. 1486"), { season: "Winter", month: 2, day: 14 }),
  record("1486-noto-storm", "disaster", "disaster", 1486, "exact-date", copy("Strong wind recorded in Noto", "บันทึกลมแรงในโนโตะ"), copy("An Noto chronicle records a strong wind on the cited date. No damage scale is inferred where the entry does not state one.", "พงศาวดารโนโตะบันทึกลมแรงในวันที่อ้างอิง จึงไม่อนุมานระดับความเสียหายหากต้นฉบับไม่ได้ระบุ."), ["noto"], disasterArchive, copy("7 October 1486", "7 ตุลาคม ค.ศ. 1486"), { season: "Autumn", month: 10, day: 7 }),
  record("1486-tanba-storm", "disaster", "disaster", 1486, "exact-date", copy("Night windstorm recorded in Tanba", "บันทึกพายุลมกลางคืนในทันบะ"), copy("A Tanba chronicle records a night windstorm. This is local environmental texture only.", "พงศาวดารทันบะบันทึกพายุลมในเวลากลางคืน ใช้เป็นเพียงรายละเอียดสิ่งแวดล้อมระดับท้องถิ่น."), ["tanba"], disasterArchive, copy("9 October 1486", "9 ตุลาคม ค.ศ. 1486"), { season: "Autumn", month: 10, day: 9 }),
  record("1487-suruga-floods", "disaster", "disaster", 1487, "year", copy("Repeated floods recorded in Suruga", "บันทึกน้ำท่วมซ้ำในซูรุกะ"), copy("A Suruga chronicle refers to three flood events in the year. Its annual precision is preserved rather than inventing individual dates.", "พงศาวดารซูรุกะกล่าวถึงน้ำท่วมสามครั้งในปีดังกล่าว จึงคงระดับความละเอียดรายปีไว้แทนการสร้างวันของแต่ละเหตุการณ์."), ["suruga"], disasterArchive),
  record("1488-dewa-mortality", "disaster", "disaster", 1488, "year", copy("Livestock and human mortality recorded in Dewa", "บันทึกการตายของสัตว์และผู้คนในเดวะ"), copy("A Dewa source reports widespread animal deaths and human illness. The source’s year-level conversion is retained without diagnosing cause.", "แหล่งข้อมูลเดวะรายงานการตายของสัตว์เป็นวงกว้างและความเจ็บป่วยของผู้คน จึงคงระดับรายปีตามแหล่งโดยไม่วินิจฉัยสาเหตุ."), ["dewa"], disasterArchive),
  record("1492-etchu-flood", "disaster", "disaster", 1492, "exact-date", copy("Heavy rain and flood recorded in Etchū", "บันทึกฝนหนักและน้ำท่วมในเอ็ตชู"), copy("An Etchū chronicle records heavy rain and flooding across the fourth to sixth months. The card is tied to the source conversion date and period note.", "พงศาวดารเอ็ตชูบันทึกฝนหนักและน้ำท่วมตั้งแต่เดือนที่สี่ถึงหก การ์ดผูกกับวันแปลงจากแหล่งและหมายเหตุช่วงเวลา."), ["etchu"], disasterArchive, copy("6 May 1492", "6 พฤษภาคม ค.ศ. 1492"), { season: "Spring", month: 5, day: 6 }),
  record("1534-kii-epidemic", "disaster", "disaster", 1534, "year", copy("Epidemic record in Kii", "บันทึกโรคระบาดในกิอิ"), copy("A Kumano chronicle records illness in spring and summer. It is source-bounded public-health context and does not initiate an outbreak in the campaign.", "พงศาวดารคุมาโนะบันทึกความเจ็บป่วยในฤดูใบไม้ผลิและฤดูร้อน เป็นบริบทสาธารณสุขที่จำกัดตามแหล่ง และไม่เริ่มโรคระบาดในแคมเปญโดยอัตโนมัติ."), ["kii"], disasterArchive),
  record("1535-suo-drought", "disaster", "disaster", 1535, "year", copy("Drought recorded in Suō", "บันทึกภัยแล้งในซูโอะ"), copy("A source records drought in Suō at year precision. The catalog does not infer food prices, harvest outcome, or political response.", "แหล่งข้อมูลบันทึกภัยแล้งในซูโอะระดับรายปี โดย catalog ไม่อนุมานราคาสินค้า ผลเก็บเกี่ยว หรือการตอบสนองทางการเมือง."), ["suo"], disasterArchive),
  record("1537-wakasa-epidemic", "disaster", "disaster", 1537, "year", copy("Epidemic recorded in Wakasa", "บันทึกโรคระบาดในวากาสะ"), copy("A Wakasa record describes winter epidemic mortality. It is retained as a source-specific annual context card.", "บันทึกวากาสะบรรยายการเสียชีวิตจากโรคระบาดในฤดูหนาว จึงเก็บเป็นการ์ดบริบทประจำปีเฉพาะตามแหล่ง."), ["wakasa"], disasterArchive),
  record("1557-ise-flood", "disaster", "disaster", 1557, "exact-date", copy("Flood damage recorded in Ise", "บันทึกความเสียหายน้ำท่วมในอิเสะ"), copy("Ise records describe a breached Miyagawa embankment, flooded homes, and deaths. It is archival context rather than a campaign-wide event trigger.", "บันทึกอิเสะบรรยายคันกั้นแม่น้ำมิยากาวะแตก บ้านเรือนถูกน้ำพัด และมีผู้เสียชีวิต เป็นบริบทจดหมายเหตุ ไม่ใช่ตัวกระตุ้นเหตุการณ์ทั่วแคมเปญ."), ["ise"], disasterArchive, copy("28 September 1557", "28 กันยายน ค.ศ. 1557"), { season: "Autumn", month: 9, day: 28 }),
  record("1605-izu-field-loss", "disaster", "disaster", 1605, "exact-date", copy("Field loss recorded in Izu island settlement", "บันทึกความเสียหายของพื้นที่นาในชุมชนเกาะอิซุ"), copy("A source records loss affecting more than half of fields in an Izu island settlement. The card preserves that limited locality rather than generalizing to all Izu.", "แหล่งข้อมูลบันทึกความเสียหายต่อพื้นที่นามากกว่าครึ่งในชุมชนเกาะแห่งหนึ่งของอิซุ การ์ดคงขอบเขตพื้นที่จำกัดนี้ไว้แทนการเหมารวมทั้งอิซุ."), ["izu"], disasterArchive, copy("3 February 1605", "3 กุมภาพันธ์ ค.ศ. 1605"), { season: "Winter", month: 2, day: 3 }),
  record("1606-tajima-flood", "disaster", "disaster", 1606, "exact-date", copy("Major flood recorded in Tajima", "บันทึกน้ำท่วมใหญ่ในทาจิมะ"), copy("A Tajima chronicle records a major flood and damage to many homes. The exact scope remains bounded by the chronicle entry.", "พงศาวดารทาจิมะบันทึกน้ำท่วมใหญ่และความเสียหายต่อบ้านเรือนจำนวนมาก ขอบเขตที่แท้จริงยังจำกัดตามบันทึกต้นทาง."), ["tajima"], disasterArchive, copy("1 August 1606", "1 สิงหาคม ค.ศ. 1606"), { season: "Summer", month: 8, day: 1 }),
  record("1612-iga-ueno-storm", "disaster", "disaster", 1612, "exact-date", copy("Windstorm damages Ueno Castle tower in Iga", "พายุลมทำลายหอคอยปราสาทอุเอโนะในอิงะ"), copy("Two historical records describe storm damage to Ueno Castle’s tower in Iga. The card reports the built-site damage without inventing a military consequence.", "บันทึกประวัติศาสตร์สองแหล่งบรรยายพายุที่ทำลายหอคอยปราสาทอุเอโนะในอิงะ การ์ดรายงานความเสียหายต่อสถานที่โดยไม่แต่งผลทางทหาร."), ["iga"], disasterArchive, copy("26 September 1612", "26 กันยายน ค.ศ. 1612"), { season: "Autumn", month: 9, day: 26 }),
  record("1586-nagato-land-survey", "event", "provincial", 1586, "year", copy("Land survey recorded in Nagato", "บันทึกการสำรวจที่ดินในนากาโตะ"), copy("A Yamaguchi Prefecture chronology records a land survey in Nagato. It provides administrative context and does not alter a player’s land, taxes, or allegiance by itself.", "ลำดับเหตุการณ์ของจังหวัดยามางูจิบันทึกการสำรวจที่ดินในนากาโตะ เป็นบริบทด้านการปกครองและไม่เปลี่ยนที่ดิน ภาษี หรือความภักดีของผู้เล่นด้วยตัวเอง."), ["nagato"], yamaguchiCulturalProperty),
  record("1585-hida-invasion", "event", "provincial", 1585, "year", copy("Hida invasion and fall of Hirosé Castle", "การบุกฮิดะและการแตกของปราสาทฮิโรเซะ"), copy("Takayama City records that Kanamori Nagachika became daimyō of Hida after the 1585 invasion, and that Miki Yoshitsuna fled after Hirosé Castle fell. The catalog leaves tactics and casualties unstated.", "เมืองทากายามะบันทึกว่าคานาโมริ นางาจิกะเป็นไดเมียวแห่งฮิดะหลังการบุก ค.ศ. 1585 และมิกิ โยชิสึนะหลบหนีหลังปราสาทฮิโรเซะแตก โดย catalog ไม่ระบุกลยุทธ์หรือจำนวนผู้สูญเสียที่ไม่มีแหล่ง."), ["hida"], takayamaCityMuseum),
  record("1550s-sado-mining-development", "event", "provincial", 1550, "year", copy("Gold and silver mine development in Sado", "การพัฒนาเหมืองทองและเงินในซาโดะ"), copy("Sado City states that development of the island’s gold and silver mines became full-scale from the mid-sixteenth century. The record intentionally avoids an exact start day and grants no player access to mineral wealth.", "เมืองซาโดะระบุว่าการพัฒนาเหมืองทองและเงินบนเกาะเริ่มเต็มรูปแบบตั้งแต่กลางคริสต์ศตวรรษที่ 16 บันทึกนี้ตั้งใจไม่ระบุวันเริ่มที่แน่ชัด และไม่มอบสิทธิ์เข้าถึงความมั่งคั่งจากเหมืองแก่ผู้เล่น."), ["sado"], sadoCityWorldHeritage),
  record("1519-awaji-guardian-fall", "event", "provincial", 1519, "year", copy("Awaji guardian falls; local warriors rise", "ผู้พิทักษ์อาวาจิล่มลงและกลุ่มนักรบท้องถิ่นก้าวขึ้น"), copy("Sumoto’s museum dates the fall of the Awaji Hosokawa guardian to 1519 and describes the subsequent rise of local warrior groups. The catalog does not label a single province-wide successor.", "พิพิธภัณฑ์เมืองซูโมโตะลงวันที่การล่มของผู้พิทักษ์โฮโซกาวะแห่งอาวาจิไว้ที่ ค.ศ. 1519 และบรรยายการก้าวขึ้นของกลุ่มนักรบท้องถิ่น โดย catalog ไม่ระบุผู้สืบอำนาจเดียวครอบคลุมทั้งแคว้น."), ["awaji"], awajiCulturalHistoryMuseum),
  record("1581-awaji-hashiba-invasion", "event", "provincial", 1581, "year", copy("Hashiba invasion of Awaji", "การบุกอาวาจิของฮาชิบะ"), copy("A museum account dates a Hashiba invasion to 1581 and records broad local capitulation. It distinguishes that date from a traditional three-day-pacification story, so the catalog avoids repeating the duration as settled fact.", "บันทึกพิพิธภัณฑ์ลงวันที่การบุกของฮาชิบะไว้ที่ ค.ศ. 1581 และระบุการยอมจำนนของกลุ่มท้องถิ่นเป็นวงกว้าง อีกทั้งแยกวันที่ออกจากเรื่องเล่าดั้งเดิมเรื่องปราบได้ในสามวัน จึงไม่ยืนยันระยะเวลานั้นเป็นข้อเท็จจริงตายตัว."), ["awaji"], awajiCulturalHistoryMuseum),
  record("1600-shima-kuki-sekigahara", "event", "provincial", 1600, "year", copy("Kuki Yoshitaka’s final year in Shima context", "ปีสุดท้ายของคูกิ โยชิทากะในบริบทชิมะ"), copy("Toba City records that Shima-born naval leader Kuki Yoshitaka aligned with the western side at Sekigahara and died after its defeat. It is regional political context, not a naval asset granted to the player.", "เมืองโทบะบันทึกว่าผู้นำกองเรือคูกิ โยชิทากะ ผู้เกิดในชิมะ อยู่ฝ่ายตะวันตกที่เซกิงาฮาระและเสียชีวิตหลังฝ่ายนั้นพ่ายแพ้ เป็นบริบทการเมืองระดับแคว้น ไม่ใช่กองเรือที่มอบให้ผู้เล่น."), ["shima"], tobaCityCulturalHeritage),
  record("1578-tango-tatebe-fall", "battle", "provincial", 1578, "year", copy("Fall of Tatebe Castle in Tango", "การแตกของปราสาททาเตเบะในทันโงะ"), copy("Maizuru local-history material dates Tatebe Castle’s fall to 1578 after conflict with Hosokawa and Akechi forces. This records a local transition without assigning a province-wide owner.", "สื่อประวัติศาสตร์ท้องถิ่นไมซูรุลงวันที่ปราสาททาเตเบะแตกไว้ที่ ค.ศ. 1578 หลังความขัดแย้งกับกองกำลังโฮโซกาวะและอาเกจิ บันทึกนี้ระบุการเปลี่ยนผ่านท้องถิ่นโดยไม่กำหนดผู้ครองทันโงะทั้งแคว้น."), ["tango"], maizuruMunicipalSchool),
  record("1591-iki-katsumoto-castle", "event", "provincial", 1591, "year", copy("Katsumoto Castle completed on Iki", "ปราสาทคัตสึโมโตะสร้างเสร็จบนอิกิ"), copy("Nagasaki Prefecture dates the completion of Katsumoto Castle to 1591 and identifies it as a logistics base for the Korea campaigns. The card does not grant player access to the base, ships, or supplies.", "จังหวัดนางาซากิลงวันที่ปราสาทคัตสึโมโตะสร้างเสร็จไว้ที่ ค.ศ. 1591 และระบุว่าเป็นฐานลอจิสติกส์สำหรับการทัพเกาหลี การ์ดนี้ไม่มอบสิทธิ์เข้าฐาน เรือ หรือเสบียงแก่ผู้เล่น."), ["iki"], nagasakiCulturalProperty),
  record("1511-funaokayama-kyoto-recapture", "battle", "provincial", 1511, "month", copy("Funaokayama conflict and Kyoto recapture", "ความขัดแย้งฟุนาโอกายามะและการยึดเกียวโตกลับ"), copy("Kyoto City’s site record states that in August 1511 Ashikaga Yoshitada and Hosokawa Takakuni attacked Hosokawa Sumimoto and Hosokawa Masakata at Funaokayama and retook Kyoto. This is Yamashiro political-military context only; it does not restore or assign authority to any player.", "บันทึกสถานที่ของนครเกียวโตระบุว่าในเดือนสิงหาคม ค.ศ. 1511 อาชิคางะ โยชิตาดะและโฮโซกาวะ ทาคาโอกุนิโจมตีโฮโซกาวะ สึมิ โมโตะกับโฮโซกาวะ มาซากาตะที่ฟุนาโอกายามะและยึดเกียวโตกลับ ใช้เป็นเพียงบริบทการเมือง–การทหารของยามาชิโระ ไม่ได้ฟื้นหรือมอบอำนาจแก่ผู้เล่น."), ["yamashiro"], kyotoCityTourism, copy("August 1511", "สิงหาคม ค.ศ. 1511"), { season: "Summer", month: 8 }),
  record("1495-ouchi-yoshioki-succession", "event", "provincial", 1495, "year", copy("Ōuchi Yoshioki succeeds in Suō", "โออุจิ โยชิโอกิสืบทอดอำนาจในซูโอะ"), copy("Yamaguchi City’s chronology records the death of Ōuchi Masahiro and Ōuchi Yoshioki’s succession in 1495. This is Suō dynastic context only, not a declaration of control over other provinces or a player allegiance.", "ลำดับเหตุการณ์ของนครยามางูจิบันทึกการเสียชีวิตของโออุจิ มาซาฮิโระและการสืบทอดของโออุจิ โยชิโอกิใน ค.ศ. 1495 ใช้เป็นบริบทการสืบทอดอำนาจในซูโอะเท่านั้น ไม่ใช่คำประกาศว่าควบคุมแคว้นอื่นหรือความภักดีของผู้เล่น."), ["suo"], yamaguchiCityTourism),
  record("1500-ashikaga-yoshitane-yamaguchi", "event", "provincial", 1500, "year", copy("Ashikaga Yoshitane enters Yamaguchi protection", "อาชิคางะ โยชิทาเนะเข้าสู่ความคุ้มครองที่ยามางูจิ"), copy("Yamaguchi City’s chronology records that Ōuchi Yoshioki received the former shogun Ashikaga Yoshitane at Shinkōji in Yamaguchi after he was driven out by the Hosokawa. The card is a Suō refuge and political-network context, not a compulsory audience for a player.", "ลำดับเหตุการณ์ของนครยามางูจิบันทึกว่าโออุจิ โยชิโอกิรับอดีตโชกุนอาชิคางะ โยชิทาเนะที่วัดชินโคจิในยามางูจิ หลังถูกโฮโซกาวะขับออกไป การ์ดนี้เป็นบริบทที่พักพิงและเครือข่ายการเมืองของซูโอะ ไม่ใช่การบังคับให้ผู้เล่นเข้าเฝ้า."), ["suo"], yamaguchiCityTourism),
  record("1507-ouchi-yoshitane-restoration", "event", "provincial", 1507, "year", copy("Ōuchi support for Ashikaga Yoshitane’s restoration", "การสนับสนุนของโออุจิต่อการฟื้นอำนาจอาชิคางะ โยชิทาเนะ"), copy("Yamaguchi City’s chronology states that Ōuchi Yoshioki supported Ashikaga Yoshitane’s restoration in 1507 and then influenced shogunal politics for eleven years. The catalog treats this as a Suō-to-capital political connection rather than a player-facing national outcome.", "ลำดับเหตุการณ์ของนครยามางูจิระบุว่าโออุจิ โยชิโอกิสนับสนุนการฟื้นอำนาจของอาชิคางะ โยชิทาเนะใน ค.ศ. 1507 และมีอิทธิพลต่อการเมืองโชกุนต่อมาอีกสิบเอ็ดปี catalog จึงใช้เป็นความเชื่อมโยงทางการเมืองจากซูโอะสู่ส่วนกลาง ไม่ใช่ผลระดับชาติที่เกิดกับผู้เล่น."), ["suo"], yamaguchiCityTourism),
  record("1518-ouchi-yoshioki-yamaguchi-return", "event", "provincial", 1518, "year", copy("Ōuchi Yoshioki returns to Yamaguchi", "โออุจิ โยชิโอกิกลับสู่ยามางูจิ"), copy("Yamaguchi City’s chronology dates Ōuchi Yoshioki’s return from Kyoto to Yamaguchi to 1518. It is a provincial political-presence card and does not assign an encounter, patronage, or resource to the player.", "ลำดับเหตุการณ์ของนครยามางูจิลงวันที่โออุจิ โยชิโอกิกลับจากเกียวโตสู่ยามางูจิไว้ที่ ค.ศ. 1518 เป็นการ์ดบริบทการปรากฏตัวทางการเมืองระดับแคว้น และไม่กำหนดการพบปะ การอุปถัมภ์ หรือทรัพยากรให้ผู้เล่น."), ["suo"], yamaguchiCityTourism),
  record("1528-ouchi-yoshitaka-succession", "event", "provincial", 1528, "year", copy("Ōuchi Yoshitaka succeeds in Suō", "โออุจิ โยชิทากะสืบทอดอำนาจในซูโอะ"), copy("Yamaguchi City’s chronology records Ōuchi Yoshioki’s death and Ōuchi Yoshitaka’s succession in 1528. The card records a Suō succession without treating its later political implications as automatic campaign facts.", "ลำดับเหตุการณ์ของนครยามางูจิบันทึกการเสียชีวิตของโออุจิ โยชิโอกิและการสืบทอดของโออุจิ โยชิทากะใน ค.ศ. 1528 การ์ดบันทึกการสืบทอดในซูโอะโดยไม่ถือว่าผลทางการเมืองภายหลังเป็นข้อเท็จจริงอัตโนมัติของแคมเปญ."), ["suo"], yamaguchiCityTourism),
  record("1585-hyuga-flood-route", "disaster", "disaster", 1585, "exact-date", copy("Flood delays a route in Hyūga", "น้ำท่วมทำให้เส้นทางล่าช้าในฮิวงะ"), copy("A Hyūga diary entry records a flood that forced a route detour before arrival in Miyazaki. The card keeps this as source-bounded local travel context and does not assign the journey to the player.", "บันทึกจากฮิวงะระบุน้ำท่วมที่ทำให้ต้องอ้อมเส้นทางก่อนถึงมิยาซากิ การ์ดนี้คงไว้เป็นบริบทการเดินทางท้องถิ่นตามแหล่ง และไม่กำหนดว่าผู้เล่นเป็นผู้เดินทางนั้น."), ["hyuga"], disasterArchive, copy("17 June 1585", "17 มิถุนายน ค.ศ. 1585"), { season: "Summer", month: 6, day: 17 }),
  record("1585-kii-storm-flood", "disaster", "disaster", 1585, "exact-date", copy("Windstorm and flooding recorded in Kii", "บันทึกพายุลมและน้ำท่วมในกิอิ"), copy("The chronology records a windstorm and flooding in Kii. It does not provide a damage scale, so the catalog does not infer one.", "ลำดับเหตุการณ์บันทึกพายุลมและน้ำท่วมในกิอิ โดยไม่ระบุขนาดความเสียหาย จึงไม่มีการอนุมานเพิ่มใน catalog."), ["kii"], disasterArchive, copy("28 June 1585", "28 มิถุนายน ค.ศ. 1585"), { season: "Summer", month: 6, day: 28 }),
  record("1585-mino-major-flood", "disaster", "disaster", 1585, "exact-date", copy("Major flooding recorded in Mino", "บันทึกน้ำท่วมใหญ่ในมิโนะ"), copy("A Mino source reports a major flood with fields, houses, and deaths affected. This is an archival report with no player-specific casualty, loss, or recovery outcome.", "แหล่งข้อมูลมิโนะรายงานน้ำท่วมใหญ่ที่กระทบพื้นที่นา บ้านเรือน และมีผู้เสียชีวิต เป็นรายงานจดหมายเหตุที่ไม่ระบุผู้สูญเสีย การสูญทรัพย์ หรือการฟื้นตัวของผู้เล่น."), ["mino"], disasterArchive, copy("18 September 1585", "18 กันยายน ค.ศ. 1585"), { season: "Autumn", month: 9, day: 18 }),
  record("1585-musashi-storm-house-damage", "disaster", "disaster", 1585, "exact-date", copy("Rain and wind damage houses in Musashi", "ฝนและลมทำความเสียหายแก่บ้านเรือนในมูซาชิ"), copy("A Musashi diary records heavy rain and wind with house damage. It is local environmental evidence, not a campaign-wide damage trigger.", "บันทึกจากมูซาชิระบุฝนหนักและลมที่ทำความเสียหายแก่บ้านเรือน เป็นหลักฐานสิ่งแวดล้อมระดับท้องถิ่น ไม่ใช่ตัวกระตุ้นความเสียหายทั้งแคมเปญ."), ["musashi"], disasterArchive, copy("20 September 1585", "20 กันยายน ค.ศ. 1585"), { season: "Autumn", month: 9, day: 20 }),
  record("1585-shimosa-wind-castle-damage", "disaster", "disaster", 1585, "exact-date", copy("Strong wind damages a castle in Shimōsa", "ลมแรงทำให้ปราสาทแห่งหนึ่งในชิโมสะเสียหาย"), copy("A Shimōsa chronicle records strong wind and castle damage, without naming a player-relevant site or providing a wider political result.", "พงศาวดารชิโมสะบันทึกลมแรงและความเสียหายของปราสาท โดยไม่ระบุสถานที่ที่เกี่ยวกับผู้เล่นหรือผลการเมืองในวงกว้าง."), ["shimosa"], disasterArchive, copy("21 September 1585", "21 กันยายน ค.ศ. 1585"), { season: "Autumn", month: 9, day: 21 }),
  record("1585-mutsu-tsunami-famine-report", "disaster", "disaster", 1585, "exact-date", copy("Tsunami and severe famine recorded in Mutsu", "บันทึกสึนามิและทุพภิกขภัยรุนแรงในมุตสึ"), copy("A Mutsu chronicle records tsunami and severe famine on the cited entry. The catalog does not infer causation, geographic extent, or an automatic disaster in the player’s scene.", "พงศาวดารมุตสึบันทึกสึนามิและทุพภิกขภัยรุนแรงใน entry ที่อ้างอิง โดย catalog ไม่อนุมานเหตุและผล ขอบเขตทางภูมิศาสตร์ หรือภัยที่เกิดในฉากของผู้เล่นโดยอัตโนมัติ."), ["mutsu"], disasterArchive, copy("21 October 1585", "21 ตุลาคม ค.ศ. 1585"), { season: "Autumn", month: 10, day: 21 }),
  record("1579-bungo-storm-flood", "disaster", "disaster", 1579, "year", copy("Windstorm and flooding recorded in Bungo", "บันทึกพายุลมและน้ำท่วมในบุงโกะ"), copy("A Bungo chronology records a windstorm and flooding at year precision. The catalog does not assign a day, damage scale, or player loss beyond that source report.", "ลำดับเหตุการณ์ของบุงโกะบันทึกพายุลมและน้ำท่วมในระดับรายปี catalog ไม่กำหนดวัน ขนาดความเสียหาย หรือความสูญเสียของผู้เล่นเกินกว่ารายงานต้นทาง."), ["bungo"], disasterArchive),
  record("1579-shimosa-persistent-floods", "disaster", "disaster", 1579, "year", copy("Persistent flooding recorded in Shimōsa", "บันทึกน้ำท่วมต่อเนื่องในชิโมสะ"), copy("The source records many years of flooding in a Shimōsa estate around this entry. This is localized archival context, not a province-wide flood simulation.", "แหล่งข้อมูลบันทึกน้ำท่วมหลายปีในที่ดินแห่งหนึ่งของชิโมสะรอบ entry นี้ เป็นบริบทจดหมายเหตุเฉพาะพื้นที่ ไม่ใช่การจำลองน้ำท่วมทั้งแคว้น."), ["shimosa"], disasterArchive),
  record("1579-musashi-hail", "disaster", "disaster", 1579, "month", copy("Large hail recorded in Musashi", "บันทึกลูกเห็บขนาดใหญ่ในมูซาชิ"), copy("A Musashi chronicle records hail described as the size of soybeans in its fifth-month entry. The card remains month precision because the source date supplies no day.", "พงศาวดารมูซาชิบันทึกลูกเห็บขนาดเท่าเมล็ดถั่วเหลืองใน entry เดือนห้า การ์ดจึงคง precision ระดับเดือน เพราะแหล่งข้อมูลไม่ระบุวัน."), ["musashi"], disasterArchive, copy("Fifth month of 1579", "เดือนห้า ค.ศ. 1579"), { season: "Summer", month: 5 }),
  record("1579-national-epidemic-report", "disaster", "disaster", 1579, "month", copy("Epidemic mortality reported across the realm", "รายงานโรคระบาดและการเสียชีวิตทั่วแผ่นดิน"), copy("A chronology reports epidemic mortality across the realm in a fifth-month entry. The catalog retains this as an attributed national report and does not start disease, assign deaths, or impose conditions in the player’s campaign.", "ลำดับเหตุการณ์รายงานโรคระบาดและการเสียชีวิตทั่วแผ่นดินใน entry เดือนห้า catalog เก็บเป็นรายงานระดับชาติที่มีแหล่งอ้างอิง และไม่เริ่มโรค กำหนดผู้เสียชีวิต หรือบังคับสภาพใดในแคมเปญของผู้เล่น."), [], disasterArchive, copy("Fifth month of 1579", "เดือนห้า ค.ศ. 1579"), { season: "Summer", month: 5 }),
  record("1579-musashi-major-flood", "disaster", "disaster", 1579, "exact-date", copy("Major flooding recorded in Musashi", "บันทึกน้ำท่วมใหญ่ในมูซาชิ"), copy("A Musashi chronicle records rain followed by major flooding. It is regional environmental context only and does not trigger a flood in play.", "พงศาวดารมูซาชิบันทึกฝนตามด้วยน้ำท่วมใหญ่ ใช้เป็นเพียงบริบทสิ่งแวดล้อมระดับแคว้น และไม่ทำให้น้ำท่วมเกิดในเกมโดยอัตโนมัติ."), ["musashi"], disasterArchive, copy("8 July 1579", "8 กรกฎาคม ค.ศ. 1579"), { season: "Summer", month: 7, day: 8 }),
  record("1579-mutsu-flood-casualty-report", "disaster", "disaster", 1579, "exact-date", copy("Flood and casualties reported in Mutsu", "รายงานน้ำท่วมและผู้เสียหายในมุตสึ"), copy("A Rikuzen source records prolonged rain, flooding, and deaths of people and horses at listed localities. The card keeps this as a bounded archival report, without creating a casualty count or player impact.", "แหล่งข้อมูลจากริกุเซ็นบันทึกฝนต่อเนื่อง น้ำท่วม และการเสียชีวิตของคนกับม้าในท้องถิ่นที่ระบุ การ์ดคงเป็นรายงานจดหมายเหตุที่จำกัดตามแหล่ง โดยไม่สร้างยอดผู้เสียหายหรือผลต่อผู้เล่น."), ["mutsu"], disasterArchive, copy("20 July 1579", "20 กรกฎาคม ค.ศ. 1579"), { season: "Summer", month: 7, day: 20 }),
  record("1579-yamato-field-flood-loss", "disaster", "disaster", 1579, "exact-date", copy("Downpour damages fields in Yamato", "ฝนหนักทำความเสียหายแก่ทุ่งนาในยามาโตะ"), copy("A Yamato diary records a severe evening downpour and field loss. It is a local historical note and does not alter a campaign harvest or inventory.", "บันทึกจากยามาโตะระบุฝนตกหนักยามเย็นและความเสียหายต่อทุ่งนา เป็นหมายเหตุประวัติศาสตร์ท้องถิ่น และไม่เปลี่ยนผลเก็บเกี่ยวหรือสัมภาระของแคมเปญ."), ["yamato"], disasterArchive, copy("26 August 1579", "26 สิงหาคม ค.ศ. 1579"), { season: "Summer", month: 8, day: 26 }),
  record("1579-bitchu-flood-delays-movement", "disaster", "disaster", 1579, "exact-date", copy("Flooding delays movement in Bitchū", "น้ำท่วมทำให้การเคลื่อนไหวล่าช้าในบิตชู"), copy("A Bitchū letter attributes delayed movement to heavy rain and flooding. The card does not assign that movement, people, or delay to the player.", "จดหมายจากบิตชูระบุว่าฝนหนักและน้ำท่วมทำให้การเคลื่อนไหวล่าช้า การ์ดไม่กำหนดการเคลื่อน บุคคล หรือความล่าช้านั้นแก่ผู้เล่น."), ["bitchu"], disasterArchive, copy("24 October 1579", "24 ตุลาคม ค.ศ. 1579"), { season: "Autumn", month: 10, day: 24 }),
  record("1588-national-epidemic-report", "disaster", "disaster", 1588, "year", copy("Epidemic reported across the realm", "รายงานโรคระบาดทั่วแผ่นดิน"), copy("A medical chronology records an epidemic across the realm at year precision. The card is an attributed report only and never creates disease, fatalities, or conditions in the player’s campaign.", "ลำดับเหตุการณ์ทางการแพทย์บันทึกโรคระบาดทั่วแผ่นดินในระดับรายปี การ์ดนี้เป็นเพียงรายงานที่มีแหล่งอ้างอิง และไม่สร้างโรค ผู้เสียชีวิต หรือสภาพบังคับในแคมเปญของผู้เล่น."), [], disasterArchive),
  record("1588-yamato-windstorm-damage", "disaster", "disaster", 1588, "exact-date", copy("Windstorm damages structures in Yamato", "พายุลมทำความเสียหายแก่สิ่งปลูกสร้างในยามาโตะ"), copy("A Yamato diary records rain, a strong wind, and damage to structures. The entry remains a local weather report, not a mandatory property loss for the campaign.", "บันทึกจากยามาโตะระบุฝน ลมแรง และความเสียหายต่อสิ่งปลูกสร้าง entry นี้คงเป็นรายงานอากาศท้องถิ่น ไม่ใช่ความเสียหายต่อทรัพย์สินที่บังคับเกิดกับแคมเปญ."), ["yamato"], disasterArchive, copy("3 March 1588", "3 มีนาคม ค.ศ. 1588"), { season: "Spring", month: 3, day: 3 }),
  record("1588-yamato-flooded-boat", "disaster", "disaster", 1588, "exact-date", copy("Flooding sinks a boat in Yamato report", "รายงานน้ำท่วมทำให้เรือล่มในยามาโตะ"), copy("A Yamato diary records a boat sinking on the Kizu River during flooding and reports fatalities. The catalog deliberately does not restate a death count or impose any player loss.", "บันทึกจากยามาโตะระบุเรือล่มในแม่น้ำคิซุระหว่างน้ำท่วมและรายงานผู้เสียชีวิต catalog ตั้งใจไม่กล่าวซ้ำยอดผู้ตายหรือกำหนดความสูญเสียแก่ผู้เล่น."), ["yamato"], disasterArchive, copy("5 March 1588", "5 มีนาคม ค.ศ. 1588"), { season: "Spring", month: 3, day: 5 }),
  record("1588-mino-snow", "disaster", "disaster", 1588, "exact-date", copy("Snow recorded in Mino", "บันทึกหิมะในมิโนะ"), copy("A Mino source records snow on the cited spring date. It is a time- and place-bounded weather record, not a regional climate assertion.", "แหล่งข้อมูลมิโนะบันทึกหิมะในวันที่อ้างอิงช่วงฤดูใบไม้ผลิ เป็นบันทึกอากาศที่จำกัดด้วยเวลาและสถานที่ ไม่ใช่ข้ออ้างภูมิอากาศทั้งแคว้น."), ["mino"], disasterArchive, copy("12 May 1588", "12 พฤษภาคม ค.ศ. 1588"), { season: "Spring", month: 5, day: 12 }),
  record("1588-yamashiro-flooded-crossings", "disaster", "disaster", 1588, "exact-date", copy("Flooded rivers disrupt crossings in Yamashiro", "แม่น้ำท่วมทำให้การข้ามทางในยามาชิโระหยุดชะงัก"), copy("A Kyoto entry records flooding in the Ōi and Kamo rivers that interrupted crossings. It is Yamashiro local-mobility context only; no player route is assumed.", "entry จากเกียวโตบันทึกน้ำท่วมแม่น้ำโออิและคาโมที่ทำให้การข้ามทางหยุดชะงัก เป็นเพียงบริบทการสัญจรท้องถิ่นของยามาชิโระ โดยไม่สมมติเส้นทางของผู้เล่น."), ["yamashiro"], disasterArchive, copy("15 May 1588", "15 พฤษภาคม ค.ศ. 1588"), { season: "Spring", month: 5, day: 15 }),
  record("1588-omi-land-water-damage", "disaster", "disaster", 1588, "exact-date", copy("Land and water damage recorded in Ōmi", "บันทึกความเสียหายจากดินและน้ำในโอมิ"), copy("An Ōmi document refers to mountain collapse, river change, and waterside damage while discussing a petition. The card preserves the source-bounded conditions without defining a larger disaster scale or outcome.", "เอกสารจากโอมิกล่าวถึงภูเขาถล่ม การเปลี่ยนทางน้ำ และความเสียหายริมฝั่งในบริบทคำร้อง การ์ดคงสภาพตามแหล่งโดยไม่กำหนดขนาดภัยหรือผลลัพธ์ที่กว้างกว่า."), ["omi"], disasterArchive, copy("18 June 1588", "18 มิถุนายน ค.ศ. 1588"), { season: "Summer", month: 6, day: 18 }),
  record("1588-yamashiro-lightning-injury-report", "disaster", "disaster", 1588, "exact-date", copy("Lightning injury report from Yamashiro", "รายงานผู้บาดเจ็บจากฟ้าผ่าในยามาชิโระ"), copy("A Kyoto diary reports lightning in Saika-chō and injuries to people. This remains a localized report and does not create an injury, storm, or public-health condition in play.", "บันทึกจากเกียวโตรายงานฟ้าผ่าในไซกะโชและผู้คนบาดเจ็บ ข้อมูลนี้คงเป็นรายงานเฉพาะพื้นที่ และไม่สร้างผู้บาดเจ็บ พายุ หรือสภาพสาธารณสุขในเกม."), ["yamashiro"], disasterArchive, copy("16 August 1588", "16 สิงหาคม ค.ศ. 1588"), { season: "Summer", month: 8, day: 16 }),
  record("1589-sanuki-hail", "disaster", "disaster", 1589, "year", copy("Rain and large hail recorded in Sanuki", "บันทึกฝนและลูกเห็บขนาดใหญ่ในซานูกิ"), copy("A Sanuki source records rain and hail described as large as chestnuts at year precision. The card does not infer crop loss or a player-facing weather event.", "แหล่งข้อมูลซานูกิบันทึกฝนและลูกเห็บขนาดเท่าลูกเกาลัดในระดับรายปี การ์ดไม่อนุมานความเสียหายต่อพืชผลหรือเหตุอากาศที่เกิดกับผู้เล่น."), ["sanuki"], disasterArchive),
  record("1589-national-hail-report", "disaster", "disaster", 1589, "year", copy("Widespread hail reported across the realm", "รายงานลูกเห็บตกกว้างขวางทั่วแผ่นดิน"), copy("A chronicle reports extensive hail for the year. It remains an attributed national report rather than a universal campaign condition.", "พงศาวดารรายงานลูกเห็บตกกว้างขวางในปีดังกล่าว ข้อมูลนี้คงเป็นรายงานระดับชาติที่มีแหล่งอ้างอิง ไม่ใช่สภาพบังคับของทุกแคมเปญ."), [], disasterArchive),
  record("1589-shinano-water-damage", "disaster", "disaster", 1589, "exact-date", copy("Water damage recorded in Shinano", "บันทึกความเสียหายจากน้ำในชินาโนะ"), copy("A Shinano document links local water damage with a relief decision. The catalog records environmental context only, not an economy change, levy, or player benefit.", "เอกสารชินาโนะเชื่อมความเสียหายจากน้ำในท้องถิ่นกับการผ่อนปรนบางประการ catalog เก็บเป็นเพียงบริบทสิ่งแวดล้อม ไม่ใช่การเปลี่ยนเศรษฐกิจ ภาษี หรือผลประโยชน์ของผู้เล่น."), ["shinano"], disasterArchive, copy("4 March 1589", "4 มีนาคม ค.ศ. 1589"), { season: "Spring", month: 3, day: 4 }),
  record("1589-yamato-drought", "disaster", "disaster", 1589, "exact-date", copy("Drought recorded in Yamato", "บันทึกภัยแล้งในยามาโตะ"), copy("A Yamato diary records continuing drought after winter. It is local environmental context and does not impose crop, water, or travel effects on play.", "บันทึกจากยามาโตะระบุภัยแล้งต่อเนื่องหลังฤดูหนาว เป็นบริบทสิ่งแวดล้อมท้องถิ่น และไม่บังคับผลต่อพืชผล น้ำ หรือการเดินทางในเกม."), ["yamato"], disasterArchive, copy("7 April 1589", "7 เมษายน ค.ศ. 1589"), { season: "Spring", month: 4, day: 7 }),
  record("1589-ise-hail", "disaster", "disaster", 1589, "exact-date", copy("Hail recorded in Ise", "บันทึกลูกเห็บในอิเสะ"), copy("An Ise chronicle records hail on the cited date. The card preserves only that source-bounded weather note.", "พงศาวดารอิเสะบันทึกลูกเห็บในวันที่อ้างอิง การ์ดคงไว้เพียงหมายเหตุอากาศที่จำกัดตามแหล่ง."), ["ise"], disasterArchive, copy("28 May 1589", "28 พฤษภาคม ค.ศ. 1589"), { season: "Spring", month: 5, day: 28 }),
  record("1593-national-water-drought-report", "disaster", "disaster", 1593, "exact-date", copy("Water and drought reported across the realm", "รายงานน้ำและภัยแล้งทั่วแผ่นดิน"), copy("A Kyoto diary characterizes the realm with both water and drought on the cited date. It is an attributed historical report, not a universal campaign condition.", "บันทึกจากเกียวโตบรรยายแผ่นดินว่าประสบทั้งน้ำและภัยแล้งในวันที่อ้างอิง เป็นรายงานประวัติศาสตร์ที่มีแหล่ง ไม่ใช่สภาพบังคับของทุกแคมเปญ."), [], disasterArchive, copy("3 September 1593", "3 กันยายน ค.ศ. 1593"), { season: "Autumn", month: 9, day: 3 }),
  record("1593-yamashiro-windstorm", "disaster", "disaster", 1593, "exact-date", copy("Windstorm recorded in Yamashiro", "บันทึกพายุลมในยามาชิโระ"), copy("A Kyoto source records a windstorm. The card is local weather context only and assigns no damage to a campaign.", "แหล่งจากเกียวโตบันทึกพายุลม การ์ดเป็นเพียงบริบทอากาศท้องถิ่น และไม่กำหนดความเสียหายแก่แคมเปญ."), ["yamashiro"], disasterArchive, copy("3 October 1593", "3 ตุลาคม ค.ศ. 1593"), { season: "Autumn", month: 10, day: 3 }),
  record("1593-yamato-rain-wind", "disaster", "disaster", 1593, "exact-date", copy("Heavy rain and wind in Yamato", "ฝนหนักและลมแรงในยามาโตะ"), copy("A Yamato diary records heavy rain and wind. It remains a localized weather note without player property or travel effects.", "บันทึกจากยามาโตะระบุฝนหนักและลมแรง เป็นหมายเหตุอากาศเฉพาะพื้นที่โดยไม่มีผลต่อทรัพย์สินหรือการเดินทางของผู้เล่น."), ["yamato"], disasterArchive, copy("3 October 1593", "3 ตุลาคม ค.ศ. 1593"), { season: "Autumn", month: 10, day: 3 }),
  record("1594-aizu-flood", "disaster", "disaster", 1594, "exact-date", copy("Flood recorded in Aizu", "บันทึกน้ำท่วมในไอซุ"), copy("A local chronicle records a major flood in Aizu over the cited dates. It is historical environmental context only and does not assign loss, travel, or land effects to a campaign.", "พงศาวดารท้องถิ่นบันทึกน้ำท่วมใหญ่ในไอซุตามวันที่อ้างอิง เป็นเพียงบริบทสิ่งแวดล้อมทางประวัติศาสตร์ และไม่กำหนดความเสียหาย การเดินทาง หรือที่ดินของแคมเปญ."), ["mutsu"], disasterArchive, copy("3–4 August 1594", "3–4 สิงหาคม ค.ศ. 1594"), { season: "Summer", month: 8, day: 3 }),
  record("1594-echigo-flood", "disaster", "disaster", 1594, "month", copy("Flood and water damage reported in Echigo", "รายงานน้ำท่วมและความเสียหายจากน้ำในเอจิโงะ"), copy("An Echigo chronicle reports flooding and water damage at month precision. The card does not carry over food, mortality, or economic consequences into play.", "พงศาวดารเอจิโงะรายงานน้ำท่วมและความเสียหายจากน้ำในระดับเดือน การ์ดไม่ถ่ายทอดผลด้านอาหาร ผู้เสียชีวิต หรือเศรษฐกิจเข้าสู่เกม."), ["echigo"], disasterArchive, copy("August 1594", "สิงหาคม ค.ศ. 1594"), { season: "Summer", month: 8 }),
  record("1594-kii-windstorm", "disaster", "disaster", 1594, "exact-date", copy("Windstorm recorded in Kii", "บันทึกพายุลมในคิอิ"), copy("A Kii chronology attributes damage to strong wind on the cited date. It supplies local weather context without player property effects.", "พงศาวดารคิอิระบุความเสียหายจากลมแรงในวันที่อ้างอิง ใช้เป็นบริบทอากาศท้องถิ่นโดยไม่มีผลต่อทรัพย์สินผู้เล่น."), ["kii"], disasterArchive, copy("7 September 1594", "7 กันยายน ค.ศ. 1594"), { season: "Autumn", month: 9, day: 7 }),
  record("1594-national-windstorm-report", "disaster", "disaster", 1594, "exact-date", copy("Sudden windstorm reported across provinces", "รายงานพายุลมฉับพลันทั่วแคว้น"), copy("A chronicle reports a sudden night windstorm across provinces. This is attributed national context, not universal campaign weather or damage.", "พงศาวดารรายงานพายุลมฉับพลันยามค่ำทั่วแคว้น เป็นบริบทระดับชาติที่มีแหล่งอ้างอิง ไม่ใช่อากาศหรือความเสียหายบังคับของทุกแคมเปญ."), [], disasterArchive, copy("10 September 1594", "10 กันยายน ค.ศ. 1594"), { season: "Autumn", month: 9, day: 10 }),
  record("1594-musashi-rain-wind", "disaster", "disaster", 1594, "exact-date", copy("Rain and wind recorded in Musashi", "บันทึกฝนและลมในมูซาชิ"), copy("An Edo diary records rain and strong wind. The province mapping is Musashi; the card stays a localized weather note.", "บันทึกจากเอโดะระบุฝนและลมแรง โดยแมปพื้นที่กับมูซาชิ การ์ดคงเป็นหมายเหตุอากาศเฉพาะพื้นที่."), ["musashi"], disasterArchive, copy("22 October 1594", "22 ตุลาคม ค.ศ. 1594"), { season: "Autumn", month: 10, day: 22 }),
  record("1595-yamashiro-flood", "disaster", "disaster", 1595, "exact-date", copy("Flood recorded in Yamashiro", "บันทึกน้ำท่วมในยามาชิโระ"), copy("Kyoto sources record flooding on the cited date. This is localized environmental context only, without any player-facing damage or travel consequence.", "แหล่งจากเกียวโตบันทึกน้ำท่วมในวันที่อ้างอิง เป็นเพียงบริบทสิ่งแวดล้อมเฉพาะพื้นที่ โดยไม่มีความเสียหายหรือผลต่อการเดินทางของผู้เล่น."), ["yamashiro"], disasterArchive, copy("13 July 1595", "13 กรกฎาคม ค.ศ. 1595"), { season: "Summer", month: 7, day: 13 }),
  record("1595-settsu-dike-failure", "disaster", "disaster", 1595, "exact-date", copy("Flooded dikes recorded in Settsu", "บันทึกคันกั้นน้ำเสียหายในเซ็ตสึ"), copy("A Settsu document reports flood-related dike failures. The card does not create repair duties, tolls, closures, or economic effects in play.", "เอกสารเซ็ตสึรายงานคันกั้นน้ำเสียหายจากน้ำท่วม การ์ดไม่สร้างภารกิจซ่อม ค่าผ่านทาง การปิดเส้นทาง หรือผลทางเศรษฐกิจในเกม."), ["settsu"], disasterArchive, copy("15 July 1595", "15 กรกฎาคม ค.ศ. 1595"), { season: "Summer", month: 7, day: 15 }),
  record("1595-mutsu-flood", "disaster", "disaster", 1595, "exact-date", copy("Major flood recorded in Mutsu", "บันทึกน้ำท่วมใหญ่ในมุตสึ"), copy("A Mutsu chronicle records a major flood. It remains an attributed local historical note with no automatic campaign loss.", "พงศาวดารมุตสึบันทึกน้ำท่วมใหญ่ ข้อมูลนี้คงเป็นหมายเหตุประวัติศาสตร์เฉพาะพื้นที่ที่มีแหล่ง ไม่สร้างความสูญเสียอัตโนมัติในแคมเปญ."), ["mutsu"], disasterArchive, copy("13 September 1595", "13 กันยายน ค.ศ. 1595"), { season: "Autumn", month: 9, day: 13 }),
  record("1595-awa-windstorm", "disaster", "disaster", 1595, "exact-date", copy("Windstorm recorded in Awa", "บันทึกพายุลมในอาวะ"), copy("An Awa document describes a severe windstorm. The catalog keeps only date, place, and weather context.", "เอกสารอาวะบรรยายพายุลมรุนแรง catalog คงไว้เพียงวัน พื้นที่ และบริบทอากาศ."), ["awa"], disasterArchive, copy("21 October 1595", "21 ตุลาคม ค.ศ. 1595"), { season: "Autumn", month: 10, day: 21 }),
  record("1566-yamashiro-storm-flood", "disaster", "disaster", 1566, "exact-date", copy("Storm and flooding reported in Yamashiro", "บันทึกพายุและน้ำท่วมในยามาชิโระ"), copy("A Yamashiro entry records rain, thunder, and major flooding. It supplies local environmental context only and does not place the player at the event.", "entry ของยามาชิโระบันทึกฝน ฟ้าร้อง และน้ำท่วมใหญ่ ใช้เป็นเพียงบริบทสิ่งแวดล้อมระดับท้องถิ่น และไม่ได้กำหนดว่าผู้เล่นอยู่ในเหตุการณ์."), ["yamashiro"], disasterArchive, copy("4 July 1566", "4 กรกฎาคม ค.ศ. 1566"), { season: "Summer", month: 7, day: 4 }),
  record("1566-national-frost-famine-chronicle", "disaster", "disaster", 1566, "exact-date", copy("Frost and severe famine reported across the realm", "บันทึกน้ำค้างแข็งและทุพภิกขภัยรุนแรงทั่วแผ่นดิน"), copy("A chronicle entry reports frost and severe famine across the realm, including a mortality formula. The catalog preserves it as a source-attributed report and does not turn the formula into a player-facing fact, casualty count, or automatic scene condition.", "entry จากพงศาวดารรายงานน้ำค้างแข็งและทุพภิกขภัยรุนแรงทั่วแผ่นดิน พร้อมถ้อยคำเกี่ยวกับการเสียชีวิต catalog เก็บไว้เป็นรายงานที่มีแหล่งอ้างอิง และไม่เปลี่ยนถ้อยคำนั้นเป็นข้อเท็จจริงต่อผู้เล่น ยอดผู้ตาย หรือสภาพฉากอัตโนมัติ."), [], disasterArchive, copy("5 July 1566", "5 กรกฎาคม ค.ศ. 1566"), { season: "Summer", month: 7, day: 5 }),
  record("1566-hitachi-famine", "disaster", "disaster", 1566, "month", copy("Famine recorded in Hitachi", "บันทึกทุพภิกขภัยในฮิตาจิ"), copy("The source records famine in Hitachi in its eighth-month entry. Because the Japanese date is month-level, the card intentionally withholds a civil day.", "แหล่งข้อมูลบันทึกทุพภิกขภัยในฮิตาจิใน entry เดือนแปด เนื่องจากวันที่ญี่ปุ่นมีเพียงระดับเดือน การ์ดจึงไม่กำหนดวันตามปฏิทินสากล."), ["hitachi"], disasterArchive, copy("Eighth month of 1566", "เดือนแปด ค.ศ. 1566"), { season: "Summer", month: 8 }),
  record("1566-musashi-flooded-routes", "disaster", "disaster", 1566, "exact-date", copy("Persistent rain and flooding obstruct routes in Musashi", "ฝนต่อเนื่องและน้ำท่วมกีดขวางเส้นทางในมูซาชิ"), copy("A Musashi letter attributes obstructed routes to continuing heavy rain and flooding. It is context for local mobility only; the source does not make any player journey or force a delay.", "จดหมายจากมูซาชิระบุว่าเส้นทางถูกกีดขวางจากฝนหนักต่อเนื่องและน้ำท่วม เป็นบริบทการสัญจรระดับท้องถิ่นเท่านั้น แหล่งข้อมูลไม่ได้กำหนดการเดินทางหรือการล่าช้าของผู้เล่น."), ["musashi"], disasterArchive, copy("24 September 1566", "24 กันยายน ค.ศ. 1566"), { season: "Autumn", month: 9, day: 24 }),
  record("1566-yamato-water-damage", "disaster", "disaster", 1566, "exact-date", copy("Prolonged rain causes water damage in Yamato", "ฝนยืดเยื้อทำให้เกิดความเสียหายจากน้ำในยามาโตะ"), copy("A Yamato diary records uninterrupted rain over several days and resulting water damage. It is a local reported condition, not a campaign-wide loss calculation.", "บันทึกจากยามาโตะระบุฝนไม่หยุดหลายวันและความเสียหายจากน้ำที่ตามมา เป็นสภาพท้องถิ่นตามรายงาน ไม่ใช่การคำนวณความสูญเสียทั้งแคมเปญ."), ["yamato"], disasterArchive, copy("14 October 1566", "14 ตุลาคม ค.ศ. 1566"), { season: "Autumn", month: 10, day: 14 }),
];

export const HISTORICAL_YEAR_LEDGER: HistoricalYearLedger[] = Array.from({ length: 1615 - 1467 + 1 }, (_, index) => {
  const year = 1467 + index;
  const recordIds = HISTORICAL_TIMELINE.filter((entry) => entry.year === year).map((entry) => entry.id);
  return { year, recordIds, status: recordIds.length ? "reviewed-events" : "no-reviewed-event" };
});

const aliases: Record<string, SengokuProvinceId> = {
  sakai: "izumi", saika: "izumi", izumi: "izumi", omi: "omi", "ōmi": "omi", owari: "owari", mikawa: "mikawa", iga: "iga", kii: "kii", yamashiro: "yamashiro", settsu: "settsu", musashi: "musashi", iyo: "iyo", shima: "shima", shinano: "shinano", kaga: "kaga", yamato: "yamato", kawachi: "kawachi", mino: "mino", harima: "harima", aki: "aki", satsuma: "satsuma", bungo: "bungo", hizen: "hizen", dewa: "dewa", mutsu: "mutsu",
};

export function timelineRegionKey(region: string): SengokuProvinceId {
  const normalized = region.toLowerCase();
  return Object.entries(aliases).find(([key]) => normalized.includes(key))?.[1] ?? "yamato";
}

export function timelineForCampaign(year: number, region: string) {
  const key = timelineRegionKey(region);
  return HISTORICAL_TIMELINE.filter((record) => record.year === year).map((record) => ({ ...record, relevance: record.regionKeys.includes(key) ? "regional" as const : "national" as const }));
}

export function historicalYearLedger(year: number) {
  return HISTORICAL_YEAR_LEDGER.find((entry) => entry.year === year) ?? { year, recordIds: [], status: "no-reviewed-event" as const };
}

export function historicalBriefForCampaign(campaign: { year: number; season: string; region: string; day: number; historicalDate?: { month: number; day: number; source: "player-confirmed" } }) {
  const ledger = historicalYearLedger(campaign.year);
  const records = timelineForCampaign(campaign.year, campaign.region);
  const exactRecords = campaign.historicalDate
    ? records.filter((entry) => entry.precision === "exact-date" && entry.month === campaign.historicalDate?.month && entry.day === campaign.historicalDate?.day)
    : [];
  const contextualRecords = records.filter((entry) => entry.precision !== "exact-date").slice(0, 4);
  const dateGate = campaign.historicalDate
    ? { kind: "player-confirmed" as const, value: `${campaign.year}-${String(campaign.historicalDate.month).padStart(2, "0")}-${String(campaign.historicalDate.day).padStart(2, "0")}` }
    : { kind: "synthetic-scene-day" as const, value: `${campaign.year} · ${campaign.season} · scene day ${campaign.day}` };
  return { ledger, dateGate, exactRecords, contextualRecords };
}
