/**
 * i18n codegen — reads the source-of-truth catalog (messages.json) and regenerates
 * the typed runtime module plus per-locale JSON files.
 *
 * Guarantees ("no wrong file, no missing language"):
 *  - Only ever writes the three AUTO-GENERATED outputs below; never touches source files.
 *  - Validates every entry: keyId format, en non-empty, th optional.
 *  - Deterministic output (sorted keys) so `pnpm i18n:check` can diff against the committed files.
 *
 * Usage: `pnpm i18n:extract`   (run after editing messages.json)
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCE = path.join(ROOT, "client/src/lib/i18n/messages.json");
const OUT_DIR = path.join(ROOT, "client/src/lib/i18n/generated");

const KEY_RE = /^[a-z0-9]+(\.[a-z0-9]+)*$/;

const raw = fs.readFileSync(SOURCE, "utf8");
const catalog = JSON.parse(raw);
const errors = [];
const entries = [];

for (const [key, value] of Object.entries(catalog)) {
  if (key === "$comment") continue;
  if (!KEY_RE.test(key)) errors.push(`key "${key}" must be lowercase dot-separated (e.g. "campaign.command")`);
  if (!value || typeof value !== "object") { errors.push(`"${key}" must be an object`); continue; }
  if (typeof value.en !== "string" || value.en.trim() === "") errors.push(`"${key}".en is REQUIRED and must be a non-empty string`);
  if (value.th !== undefined && typeof value.th !== "string") errors.push(`"${key}".th must be a string ("" = not translated yet)`);
  if (value.en !== undefined && /[\t\n]/.test(value.en)) errors.push(`"${key}".en must be single-line`);
  entries.push({ key, en: value.en ?? "", th: typeof value.th === "string" ? value.th : "" });
}

if (errors.length) {
  console.error(`i18n:extract FAILED — ${errors.length} problem(s) in messages.json:`);
  for (const error of errors) console.error(`  - ${error}`);
  process.exit(1);
}

entries.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));

const asConst = (rows) => `{\n${rows.map(({ key, ...rest }) => `  ${JSON.stringify(key)}: ${JSON.stringify(rest)}`).join(",\n")}\n}`;
const byLocale = (locale) => Object.fromEntries(entries.map(({ key }) => [key, catalog[key][locale] ?? ""]));

const generatedTs = `// AUTO-GENERATED by \`pnpm i18n:extract\` — DO NOT EDIT THIS FILE.
// Edit client/src/lib/i18n/messages.json instead, then re-run the script.
export const uiMessages = ${asConst(entries)} as const;

export type UiMessageKey = keyof typeof uiMessages;
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, "messages.ts"), generatedTs, "utf8");
fs.writeFileSync(path.join(OUT_DIR, "en.json"), JSON.stringify(byLocale("en"), null, 2) + "\n", "utf8");
fs.writeFileSync(path.join(OUT_DIR, "th.json"), JSON.stringify(byLocale("th"), null, 2) + "\n", "utf8");

const pending = entries.filter(({ th }) => th === "").length;
console.log(`i18n:extract OK — ${entries.length} keys (${entries.length - pending} translated to th, ${pending} pending en-fallback).`);
